### ISSUE TITLE
progress prop no longer working after update

### ISSUE THREAD

**Issue by xtl-geiger** [lottie-react-native/lottie-react-native#1125]
### Description

After I updated react-native and lottie-react-native to the latest versions I can no longer use the progress prop but only autoplay.
I did not change the code at all. It used to work fine.
I used to use lottie 5.1.x and updated to 6.3.1.

### Steps to Reproduce

Try to set progress with newest versions.

**Expected behavior:** 
The animation to render using progress prop.

**Actual behavior:**
App is crashing. 

![Screenshot_1698409025](https://github.com/lottie-react-native/lottie-react-native/assets/35232135/46d6f5d6-b80e-4dec-9c45-52e7a3a287cf)

Terminal output:
`TypeError: Cannot add new property '_tracking', js engine: hermes`

### React Native Environment

Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.8
    wanted: ^11.3.2
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

### Lottie Version

Version: 6.3.1

**Comment by lordprana** [comment]
Martin, I've read the information at the link you provided and the information is not obvious on how to fix this issue. Would you please explain here?

**Comment by TheRogue76** [comment]
Maybe this will help a bit: https://github.com/lottie-react-native/lottie-react-native/blob/master/MIGRATION-5-TO-6.md
The jist of it is: Lottie React Native no longer wraps the component with a `createAnimatedComponent`, since that implementation was using React Native's `createAnimatedComponent` and people wanted to use Reanimated.
If all you care about is compatibility, you can make your lottie component animated again by doing:
```ts
const AnimatedLottieView = Animated.createAnimatedComponent(LottieView)
```
And using AnimatedLottieView instead and it will work just like before. If you want to use Reanimated and make the progess a shared value, you can do that as well. Let me know if that was enough @lordprana
