### ISSUE TITLE
Invariant Violation: requireNativeComponent: "LottieAnimationView" was not found in the UIManager.

### ISSUE THREAD

**Issue by JsirForGit** [lottie-react-native/lottie-react-native#1167]
### Description

Invariant Violation: requireNativeComponent: "LottieAnimationView" was not found in the UIManager.

### Steps to Reproduce

1. yarn add lottie-react-native
2. cd ios & pod install

I tried to delete the node_modules and pods folders and re-install still won't run

**Expected behavior:** Get the correct rendering 

**Actual behavior:**  get Error Invariant Violation: requireNativeComponent: "LottieAnimationView" was not found in the UIManager.

### React Native Environment

"react": "18.2.0",
"react-native": "0.72.4",

### Lottie Version

Version: 6.5.1

**Comment by AjayGol** [comment]
I have issue in my project today Lottie file is not playing automatically. no any changes for my code level

**Comment by TheRogue76** [comment]
> @TheRogue76
> 
> I have issue in my project today Lottie file is not playing. no any changes for my code level. I have also check for live app. Check on IOS

@AjayGol Are you and @JsirForGit working on the same app? or is it a different one? If it is a different one please open an issue with all the required bits of information (I really can not do anything unless i have something to debug). If it's the same one, i ask that only one of you comments on the issue so that the communication doesn't fall apart

**Comment by TheRogue76** [comment]
Just to be double sure here is a fresh project with React Native 0.72.4 and Lottie 6.5.1:
https://github.com/TheRogue76/test-lottie-072
<img width="1728" alt="Screenshot 2024-01-24 at 14 14 18" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/0dd65cb3-3309-42cf-8dd7-953e1d619295">
So please provide the needed info, otherwise i really can't help

**Comment by JsirForGit** [comment]
> Hi @JsirForGit. Did you install Lottie fresh or were you upgrading your setup? You didn't add any reproducers and your React Native Environment doesn't tell me much, so the help i can provide is rather limited (We do have CI checks and as far as i see it is working fine on 0.72, so i guess something else is messed up in your setup) In the meantime, if you can not provide a reproducer, delete your node modules, the yarn.lockfile, Derived data for Xcode, and Both the Pods folder and the Podfile.lock and do a fresh install of everything. If that doesn't solve it, please provide more information so i can help with the debugging experience

This is the first time my project has been connected to Lottie. I just executed `yarn add lottie-react-native` and `pod install` in the ios folder。now I use lottie 5.1.6 & lottie-ios， this is OK。

**Comment by opauloantonio** [comment]
I tried to upgrade to v6 a few months ago and got this error too, so I decided to stay on v5 for a while. Today I tried to upgrade again and had the same error. I noticed that after upgrading the lib and running `pod install`, it would remove both `lottie-ios` and `lottie-react-native` from the `Podfile.lock`, so I guess for some reason, the dependencies in v6 were not being downloaded correctly.

Tried to suggestions on #995 but they didn't work either. What worked for me was putting this line:
```
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native' 
```
on my `Podfile`.

After doing that and running `pod install` again, `lottie-react-native` came back to the `Podfile.lock` and the lib started working again.

Not sure if I missed this step somewhere, I don't think it's in the migration guide and v5 was working fine without this, I also don't know if that's the correct way to solve this or if something else should fixed in my project or in the lib, but it's working now.

**Comment by TheRogue76** [comment]
> I tried to upgrade to v6 a few months ago and got this error too, so I decided to stay on v5 for a while. Today I tried to upgrade again and had the same error. I noticed that after upgrading the lib and running `pod install`, it would remove both `lottie-ios` and `lottie-react-native` from the `Podfile.lock`, so I guess for some reason, the dependencies in v6 were not being downloaded correctly.
> 
> Tried to suggestions on #995 but they didn't work either. What worked for me was putting this line:
> 
> ```
> pod 'lottie-react-native', :path => '../node_modules/lottie-react-native' 
> ```
> 
> on my `Podfile`.
> 
> After doing that and running `pod install` again, `lottie-react-native` came back to the `Podfile.lock` and the lib started working again.
> 
> Not sure if I missed this step somewhere, I don't think it's in the migration guide and v5 was working fine without this, I also don't know if that's the correct way to solve this or if something else should fixed in my project or in the lib, but it's working now.

Sounds like the cache on the pod and the node module got messed up. I'd have to see a reproducible to be able to debug it correctly, but wild guess? Delete your podfile.lock and the Pod directory in your ios app, clean out the node modules and your yarn.lock or package-lock.json or whatever else, and do a clean install. It's important to delete the lock files, since yarn in particular has this aggressive behavior where even running install with new dependencies doesn't always delete the old stuff

**Comment by ekpono** [comment]
I had the same error and downgraded from `6.7.2` to `5.1.6` and it worked
