### ISSUE TITLE
Possible to change colorFilters dynamically without reseting animation?

### ISSUE THREAD

**Issue by bumpingChris** [lottie-react-native/lottie-react-native#1198]
### Description
blobColor below is a state variable that contains a color string that changes based on user input. However, everytime it changes, the lottie animation resets. Is there a way to dynamically change the lottie color without reseting the animation?

`<LottieView
        style={{ width: 300, height: 300, position: 'absolute' }}
        source={blobLottie}
        colorFilters={[
            {
              keypath: 'Blob 3', 
              color: blobColor ? blobColor : "#FF0000",
            }
          ]}
        autoPlay={true}
        loop={true}
        ref={ref => (_lottieRef.current = ref)}
    />`

**Comment by TheRogue76** [comment]
Interesting question. I haven't had the time to look too deep in the code for this particular use case, but I can tell that we are not resetting the view upon colorFilter application. My guess? Could be that React Native is destroying and rebuilding the Lottie view since the props have changed and that is causing it to reset. Can you try making the Lottie view animated (With Reanimated or the Animated API) and animate the change in color and report back? That might circumvent the rerender trigger.
