### ISSUE TITLE
^6.7.2 > Getting error in xCode: 'CALayerContentsGravity' is only available in iOS 12.0 or newer

### ISSUE THREAD

**Issue by aurangblackbuck** [lottie-react-native/lottie-react-native#1243]
### Description

I updated the react-native-lottie to the latest version: ^6.7.2
I am using react-native: 0.72.4

My project's minimum deployment target is set to: iOS 13

error in xCode: 'CALayerContentsGravity' is only available in iOS 12.0 or newer

![Screenshot 2024-06-22 at 12 25 54](https://github.com/lottie-react-native/lottie-react-native/assets/151621755/746a7ce6-fd70-4633-9ef5-b6ca449afb9c)

### Steps to reproduce

1. Update the react-native-lottie to latest (^6.7.2)
2. Install pods success
3. run app in xCode: build error

### Lottie React Native version

6.7.2

### React Native version

0.72.4

### Platforms

iOS

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by aurangblackbuck** [comment]
I already read: [THIS](https://github.com/airbnb/lottie-ios/issues/2435#issuecomment-2173428280) comment but still, there is no solution.

**Comment by TheRogue76** [comment]
I'd say give it some time while Xcode 16 is in beta. A [PR](https://github.com/lottie-react-native/lottie-react-native/pull/1238) has been merged to master to bump LRN to 4.4.3 with minimum iOS 13.4 requirements, but a bunch of stuff needs to be done before we can release a new version, and we won't release one while the tool chain is still being developed by Apple:
1. Get rid of this crappy hack: https://github.com/lottie-react-native/lottie-react-native/blob/3d30065b48a1a1fd592fd90f22372d33dbe6b3b1/packages/core/lottie-react-native.podspec#L5
2. Fix the CI pipeline for new arch and old arch (the react native versions need a bump, and this needs an overhaul to xcode 15 at minimum to be able to build again, since Swift 5.9 is the new minimum target).
3. Updated release notes letting people know to only update to 7.0.0 if they are 0.73 and above.
4. Add VisionOS support (been waiting for some stuff that are now finally out)

If you are feeling eager, any help on those things is super appreciated.

**Comment by TheRogue76** [comment]
Should be resolved in V7 that was just released. We added a github action runner for Xcode 16 juuuuust to be safe, so if it breaks, we will know, but so far it is running fine on the RC for Xcode 16
