### ISSUE TITLE
Lottie files don't play (or work at all) on Android if width or height is a not-whole number

### ISSUE THREAD

**Issue by jvgeee** [lottie-react-native/lottie-react-native#1265]
### Description

I've been having issues with various lottie files displaying on React Native in Android (not IOS), and it only happened for some files and not others.

I checked the feature compatibility chart to make sure we weren't using any After Effects features that weren't compatible with Android, but no dice.

Eventually I stumbled across [this issue](https://github.com/lottie-react-native/lottie-react-native/issues/1159), which matched my issues completely.

Example animation: https://app.lottiefiles.com/share/de484dcb-86d0-462e-9cc0-3cb84fadba03

The user eventually resolved their issue by editing their lottie file to have a full-number for width and height.

However, this isn't documented anywhere on the `lottie-react-native` docs that I can find, nor is it intuitive. If my designer makes a lottie animation for me to use in the app, I expect it to work if I've followed all of `lottie-react-native`'s setup steps. 

This is a bug that should be addressed, either by rounding the width/height automatically within LRN (preferred) or by adding to the documentation that this is a known issue on Android that won't be fixed (not-preferred).

### Steps to reproduce

1. Create a lottie file with non-whole numbers for width and height, e.g. `"h":90.84,"w":97.12`
2. Try to load it into lottie-react-native on Android
3. It won't work

### Lottie React Native version

6.7.2

### React Native version

0.73.1

### Platforms

Android

### Workflow

Expo Dev Client

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Acknowledgements

Yes

**Comment by TheRogue76** [comment]
Hi @jvgeee 

While I understand your frustration, reality is that Lottie RN just uses whatever behavior Lottie Android and Lottie iOS have on their perspective platforms. A solution that edits the file is not viable because A) What about files that are not locally loaded JSONs (like remote files or dotlottie files), you can not edit those B) Who is to say what the correct behavior is at that point? Rounding is making an assumption, one that is not shared on any of the underlying platforms.
If you wish, I can add a line under the README's trouble shooting, but that is about as far as we can do on this side. There are logs provided by the underlying SDKs in Log cat / iOS's console that will show up naturally, if that is of any use. However we can not implement any change that goes against the spec

**Comment by jvgeee** [comment]
@TheRogue76 That's totally fine, I understand the reason for not wanting to edit the files. Adding it to the documentation would be a great first step.
