### ISSUE TITLE
Make Podfile work without using use_frameworks! for archiving to TestFlight.

### ISSUE THREAD

**Issue by AlgoSolu** [lottie-react-native/lottie-react-native#620]
### Description

No workaround found about archiving project which is using lottie-react-native on Xcode with Podfile. Currently, we have to add `use_frameworks! ` to Podfile to make it run...  The problem comes when we try to upload app to TestFlight. The build has this folder empty and Apple refuse to upload this file to TestFlight:
<img width="142" alt="Capture d’écran, le 2020-03-25 à 17 44 46" src="https://user-images.githubusercontent.com/7544240/77588483-52ca7e80-6ec0-11ea-9ffc-75b96f6af840.png">

When we use `use_frameworks!`, everything works, but the file upload is ~600% bigger than when we not use` use_frameworks!`. 

**Expected behavior:**
Archiving project to TestFlight it without `use_frameworks!` in Podfile.

**Actual behavior:** see description

### Versions

You can get this information from executing `npm: '6.14.2',`.

**Comment by betoharres** [comment]
that'd be nice too in order to be able to upgrade to the latest RN 0.62 and also use `Flipper`

**Comment by emilioicai** [comment]
@betoharres @DonavanMartin I'm using Lottie in several projects and on none of them I have `use_frameworks!` set up. Could you explain a bit why you need it?

**Comment by betoharres** [comment]
@emilioicai oh sorry about that, I didn't have any problems with the library actually! I was just looking at this library issues before trying to use it; I had a similar problem with another `react-native-community` package. Details: https://github.com/react-native-community/react-native-text-input-mask/issues/155
and this issue here was the only issue aimed to `use_frameworks!` that was created recently, so I thought it would be better to just comment that instead of creating a new issue!

**Comment by andersonaddo** [comment]
Any update on this? Has a workaround been found?
