### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by jeffreyabarrios** [lottie-react-native/lottie-react-native#793]
### Description

When trying to install the latest (4.0.3), I get the following error:

`[!] The platform of the target 'TVProject' is not compatible with 'lottie-react-native (4.0.3)', which does not support 'tvOS'.`

Is there any fix for this?

### Steps to Reproduce

1. npm install lottie-react-native 
2. npm install lottie-ios@3.2.3  
3. cd ios && pod install

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

4.0.3.

**Comment by jeffreyabarrios** [comment]
Does anyone has an idea or a solution for this?

**Comment by godwin-codeprism** [comment]
> Does anyone has an idea or a solution for this?

Found a temporary fix for this. Thanks to [DiceTechnology](https://github.com/DiceTechnology/lottie-react-native/tree/feat/add-tvos-suppoort)

### Follow these steps

1. In your node_modules go to `node_modules/lottie-react-native/lottie-react-native.podspec`
2. And add this  👉   `s.platforms = { :ios => "9.0", :tvos => "9.0" }` in line number 13 under `s.license      = package['license']`
3. Delete `Pods` and `podfile.lock` under ios folder
4. Then run `pod install` under ios folder
5. Clean and Rebuild you tv-os app. It should be working. 
6. (Optional) You might also want to use a package like [patch-package](https://github.com/ds300/patch-package) in order to retain this change even after running `npm install`.  

Hope it helps. Cheers 🍻

**Comment by emilioicai** [comment]
Can you guys try with latest version (4.1.3)?
